@host=https://localhost:7115

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Ömer Faruk",
    "lastName":"Çelik",
    "email":"email@email.com",
    "password":"pass123"
}